#!/usr/bin/env python3
"""Rewrite the roster block, the sitemap and the robots sitemap list from fleet.json."""
import html
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fleet  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
R = json.loads((ROOT / "fleet.json").read_text(encoding="utf-8"))
E = html.escape

LANES = [("directory", "The directories"), ("meta", "The whole shelf"),
         ("product", "The assistants"), ("company", "The companies")]


def block() -> str:
    out = ['<!-- FLEET:BEGIN — generated by tools/build_fleet.py from fleet.json -->',
           '<section id="directories">', '  <div class="wrap">',
           '    <p class="h-eyebrow">The Shelf</p>',
           '    <h2 class="h-title">The directories</h2>',
           '    <p class="ledger-sub">Each one is a corpus: records with their sources, under a share-alike licence. '
           f'All of it counted in one place: <a href="{E(R["index"])}">the index</a>.</p>',
           '    <div class="fleet-grid">']
    for lane, _ in LANES:
        for s in R["sites"]:
            if s.get("lane") != lane or s["id"] == "portal":
                continue
            name = E(s["name"]) + (f' <span class="th">{E(s["th"])}</span>' if s.get("th") else "")
            out.append(f'      <a class="fleet-card" href="{E(s["url"])}"><b>{name}</b><span>{E(s["note"])}</span></a>')
    out += ['    </div>',
            '    ' + fleet.support_html(roster=R),
            '  </div>', '</section>', '<!-- FLEET:END -->']
    return "\n".join(out)


CSS = """
  .fleet-grid{ display:grid; gap:14px; grid-template-columns:repeat(auto-fill,minmax(15rem,1fr)) }
  .fleet-card{ display:block; border-radius:var(--r); padding:16px 18px; border:1px solid var(--glass-line);
    text-decoration:none; color:inherit }
  .fleet-card b{ display:block; font-family:var(--serif); font-size:17px; margin-bottom:.25rem }
  .fleet-card span{ display:block; font-size:13.5px; opacity:.78; line-height:1.55 }
  .fleet-card .th{ opacity:.7; font-size:14px }
  .fleet-card:hover{ border-color:var(--gold,#e7c66c) }
  .support{ margin-top:18px; text-align:center; font-size:13.5px; opacity:.8 }
  .support a{ margin:0 .3rem }
"""


def main() -> int:
    p = ROOT / "index.html"
    s = p.read_text(encoding="utf-8")

    if "FLEET:BEGIN" in s:
        s = re.sub(r"<!-- FLEET:BEGIN.*?<!-- FLEET:END -->", block(), s, flags=re.S)
    else:
        s = s.replace('<!-- ============================================================= HODIE LEDGER -->',
                      block() + '\n\n<!-- ============================================================= HODIE LEDGER -->', 1)
    if ".fleet-grid{" not in s:
        s = s.replace("  .exits{ display:grid;", CSS + "  .exits{ display:grid;", 1)

    # one entity, every surface: Person.sameAs across the whole roster
    same = ["https://github.com/NaNoBotCo"] + [x["url"].rstrip("/") for x in R["sites"] if x["id"] != "portal"]
    s = re.sub(r'"sameAs": \["https://github\.com/NaNoBotCo"[^\]]*\]',
               '"sameAs": [' + ", ".join(json.dumps(u) for u in same) + ']', s, count=1)

    p.write_text(s, encoding="utf-8")

    # sitemap: the portal's own page, then every sibling home
    urls = ["https://nanobotco.github.io/"] + [x["url"] for x in R["sites"]
                                               if x["url"].startswith("https://nanobotco.github.io/") and x["id"] != "portal"]
    urls += ["https://nan.wichaa.net/", "https://nan.wichaa.net/thairoots/", "https://nan.wichaa.net/skipdjt/"]
    sm = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        sm.append(f"  <url><loc>{E(u)}</loc><changefreq>weekly</changefreq></url>")
    sm.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(sm) + "\n", encoding="utf-8")

    rb = ROOT / "robots.txt"
    t = re.sub(r"(?m)^Sitemap: .*\n?", "", rb.read_text(encoding="utf-8")).rstrip()
    rb.write_text(t + "\n\n" + fleet.robots_lines("portal", roster=R)
                  + "Sitemap: https://nan.wichaa.net/sitemap.xml\n", encoding="utf-8")


    # the roster, in the brief the machines read
    lp = ROOT / "llms.txt"
    lt = lp.read_text(encoding="utf-8")
    sec = fleet.llms_section("portal", heading="## The directories", roster=R)
    if fleet.MARK in lt:
        lt = lt.split(fleet.MARK)[0].rstrip() + "\n"
    lp.write_text(lt.rstrip() + "\n\n" + fleet.MARK + "\n" + sec + "\n", encoding="utf-8")

    # the roster, served from the portal too
    (ROOT / "fleet.json").write_text(json.dumps(R, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"portal: {len(R['sites'])} sites in the block, {len(urls)} urls in sitemap.xml, robots rewritten")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
